services:

  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--experimental.localPlugins.traefikclassifier.moduleName=github.com/WebConcern/traefikclassifier"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../.:/plugins-local/src/github.com/WebConcern/traefikclassifier"
    networks:
      - traefikclassifier_example

  whoami:
    image: "traefik/whoami"
    container_name: "traefik-whoami"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.middlewares.traefikclassifier.plugin.traefikclassifier.cityDbPath=/plugins-local/src/github.com/WebConcern/traefikclassifier/data/mmdb/GeoLite2-City.mmdb"
      - "traefik.http.middlewares.traefikclassifier.plugin.traefikclassifier.asnDbPath=/plugins-local/src/github.com/WebConcern/traefikclassifier/data/mmdb/GeoLite2-ASN.mmdb"
      - "traefik.http.routers.whoami.middlewares=traefikclassifier"
    networks:
      - traefikclassifier_example

networks:
  traefikclassifier_example:
    name: traefikclassifier_example
    driver: bridge
