type: middleware
import: github.com/WebConcern/traefikclassifier

name: traefikclassifier
displayName: Traefik Classifier
summary: 'GeoIP lookups and traffic classification (datacenter, VPN, Tor, AI crawler detection).'

testData:
  cityDbPath: 'data/mmdb/GeoLite2-City.mmdb'
  asnDbPath: 'data/mmdb/GeoLite2-ASN.mmdb'
